# Generated by Django 5.2.16 on 2026-08-03 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('limits', models.JSONField(default=dict, help_text='items, storage_bytes, monthly_harness_turns, embedding_tokens, concurrent_jobs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'control_plan',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('trialing', 'Trialing')], default='active', max_length=32)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(db_column='plan_code', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', to_field='code')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'control_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('counters', models.JSONField(default=dict, help_text='harness_turns, embedding_tokens, storage_bytes, concurrent_jobs, ...')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='usage_rows', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'control_usage',
                'unique_together': {('tenant', 'period_start', 'period_end')},
            },
        ),
    ]
