# Generated by Django 5.2.17 on 2026-09-01 04:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orchestration', '0003_job_output_artifact_key'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('atlas', 'ATLAS'), ('typed', 'Typed')], max_length=16)),
                ('contract_version', models.CharField(default='theorem.extraction.v1', max_length=64)),
                ('source_kind', models.CharField(choices=[('artifact', 'Artifact'), ('web_corpus', 'Web corpus'), ('life_email', 'Life email')], max_length=32)),
                ('source_ref', models.JSONField(default=dict)),
                ('params', models.JSONField(default=dict)),
                ('params_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('partial', 'Partial'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=16)),
                ('shard_count', models.PositiveIntegerField(default=0)),
                ('rows_total', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'control_extractionjob',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_digest', models.CharField(db_index=True, max_length=71)),
                ('claim_id', models.CharField(blank=True, max_length=512, null=True)),
                ('decision', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('merge_into', 'Merge into')], max_length=16)),
                ('merge_target_claim_id', models.CharField(blank=True, max_length=512, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('reviewer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='extraction.extractionjob')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='extraction_reviews', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'control_extractionreview',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionShard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('input_artifact_key', models.CharField(max_length=512)),
                ('input_digest', models.CharField(max_length=71)),
                ('input_schema_json', models.TextField()),
                ('input_rows', models.PositiveIntegerField()),
                ('output_artifact_key', models.CharField(blank=True, default='', max_length=512)),
                ('output_rows', models.PositiveIntegerField(blank=True, null=True)),
                ('output_digest', models.CharField(blank=True, default='', max_length=71)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('superseded', 'Superseded')], default='queued', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shards', to='extraction.extractionjob')),
                ('orchestration_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extraction_shard', to='orchestration.job')),
            ],
            options={
                'db_table': 'control_extractionshard',
                'ordering': ['job_id', 'index'],
            },
        ),
        migrations.AddConstraint(
            model_name='extractionjob',
            constraint=models.UniqueConstraint(fields=('tenant', 'operation', 'params_hash', 'source_ref'), name='control_extract_job_idempotent_uniq'),
        ),
        migrations.AddConstraint(
            model_name='extractionreview',
            constraint=models.UniqueConstraint(fields=('tenant', 'candidate_digest', 'created_at'), name='control_extract_review_recency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='extractionshard',
            constraint=models.UniqueConstraint(fields=('job', 'index'), name='control_extract_shard_job_index_uniq'),
        ),
    ]
