# Generated by Django 5.2.17 on 2026-09-02 18:42

import hashlib

from django.db import migrations, models


def grant_error_column(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM pg_roles WHERE rolname = 'theorem_spine'")
        if cursor.fetchone() is not None:
            cursor.execute(
                "GRANT SELECT (error) ON control.control_extractionjob "
                "TO theorem_spine"
            )
            cursor.execute(
                "GRANT SELECT (candidate_digest_version) "
                "ON control.control_extractionreview TO theorem_spine"
            )


def revoke_error_column(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM pg_roles WHERE rolname = 'theorem_spine'")
        if cursor.fetchone() is not None:
            cursor.execute(
                "REVOKE SELECT (candidate_digest_version) "
                "ON control.control_extractionreview FROM theorem_spine"
            )
            cursor.execute(
                "REVOKE SELECT (error) ON control.control_extractionjob "
                "FROM theorem_spine"
            )


def prepare_legacy_uniqueness(apps, schema_editor):
    extraction_job = apps.get_model('extraction', 'ExtractionJob')
    connection = schema_editor.connection if schema_editor is not None else None
    if connection is not None and connection.vendor == 'postgresql':
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT id
                FROM (
                    SELECT id,
                           ROW_NUMBER() OVER (
                               PARTITION BY tenant_id, operation, params_hash, source_ref
                               ORDER BY created_at, id
                           ) AS collision_rank
                    FROM control.control_extractionjob
                ) AS ranked
                WHERE collision_rank > 1
                """
            )
            duplicate_ids = [row[0] for row in cursor.fetchall()]
    else:
        duplicate_ids = []
        seen = []
        for job in extraction_job.objects.order_by('created_at', 'id').iterator():
            identity = (job.tenant_id, job.operation, job.params_hash)
            if any(
                identity == prior_identity and job.source_ref == prior_source_ref
                for prior_identity, prior_source_ref in seen
            ):
                duplicate_ids.append(job.id)
            else:
                seen.append((identity, job.source_ref))

    for job in extraction_job.objects.filter(id__in=duplicate_ids).iterator():
        rollback_identity = (
            f"theorem.extraction.rollback:{job.params_hash}:"
            f"{job.source_kind}:{job.id}"
        )
        job.params_hash = hashlib.sha256(
            rollback_identity.encode('utf-8')
        ).hexdigest()
        job.save(update_fields=['params_hash'])


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='extractionjob',
            name='control_extract_job_idempotent_uniq',
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            prepare_legacy_uniqueness,
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='extractionreview',
            name='candidate_digest_version',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extractionreview',
            name='candidate_digest_version',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddConstraint(
            model_name='extractionjob',
            constraint=models.UniqueConstraint(fields=('tenant', 'operation', 'source_kind', 'params_hash', 'source_ref'), name='control_extract_job_idempotent_uniq'),
        ),
        migrations.RunPython(grant_error_column, revoke_error_column),
    ]
