# Generated by Django 5.2.17 on 2026-09-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='extractionjob',
            name='control_extract_job_idempotent_uniq',
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='extractionjob',
            constraint=models.UniqueConstraint(fields=('tenant', 'operation', 'source_kind', 'params_hash', 'source_ref'), name='control_extract_job_idempotent_uniq'),
        ),
    ]
