# Generated by Django 5.2.17 on 2026-09-06 02:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0002_remove_extractionjob_control_extract_job_idempotent_uniq_and_more'),
        ('orchestration', '0003_job_output_artifact_key'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capture_kind', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('url', 'URL')], max_length=8)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('source_text', models.TextField(blank=True)),
                ('artifact_key', models.CharField(blank=True, max_length=512)),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('source_sha256', models.CharField(max_length=64)),
                ('filename', models.CharField(blank=True, max_length=512)),
                ('media_type', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(default=dict)),
                ('ingestion_status', models.CharField(choices=[('captured', 'Captured'), ('parsed', 'Parsed'), ('extracted', 'Extracted'), ('failed', 'Failed')], default='captured', max_length=16)),
                ('parsed_tree', models.JSONField(default=dict)),
                ('layers', models.JSONField(default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_artifacts', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'control_capture_artifact',
            },
        ),
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('admission', 'Admission'), ('claim_escalation', 'Claim escalation')], default='admission', max_length=24)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('object_types', models.JSONField(default=list)),
                ('stage_history', models.JSONField(default=list)),
                ('parser_receipt', models.JSONField(default=dict)),
                ('output', models.JSONField(default=dict)),
                ('ambiguity', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='extraction.artifact')),
                ('orchestration_job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='document_extraction_run', to='orchestration.job')),
            ],
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_sha256'), name='control_capture_tenant_digest_uniq'),
        ),
    ]
