# Generated by Django 5.2 for the theorem.competence.v1 contract.
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetenceJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[("fit", "Fit"), ("refit", "Refit")],
                        max_length=16,
                    ),
                ),
                ("operation_id", models.CharField(db_index=True, max_length=128)),
                ("request_digest", models.CharField(max_length=71)),
                ("request_json", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refused", "Refused"),
                            ("canceled", "Canceled"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("scorer_json", models.JSONField(blank=True, default=dict)),
                ("refusal_json", models.JSONField(blank=True, default=dict)),
                ("artifact_keys_json", models.JSONField(blank=True, default=dict)),
                (
                    "cleanup_request_digest",
                    models.CharField(blank=True, default="", max_length=71),
                ),
                ("cleanup_receipt_json", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        db_column="project_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competence_jobs",
                        to="tenancy.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competence_jobs",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "control_competence_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="competencejob",
            constraint=models.UniqueConstraint(
                fields=("tenant", "operation_id"),
                name="control_competence_job_tenant_operation_uniq",
            ),
        ),
    ]
