# Generated by Django 5.2 for W14 competence worker recovery.
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competencejob",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="competencejob",
            name="celery_task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
