# Generated by Django 5.2.16 on 2026-08-04 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_hash', models.CharField(max_length=128)),
                ('subject_user_id', models.CharField(help_text='WorkOS user id being impersonated', max_length=128)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('audit_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_grants_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_grants', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'control_impersonationgrant',
                'ordering': ['-created_at'],
            },
        ),
    ]
