# Generated by Django 5.2.16 on 2026-08-03 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=255)),
                ('operation_id', models.CharField(db_index=True, help_text='Idempotency key from cache_key_for_operation', max_length=128, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=32)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('input_payload_digest', models.CharField(blank=True, default='', max_length=128)),
                ('output_schema_json', models.TextField(blank=True, default='')),
                ('output_payload_digest', models.CharField(blank=True, default='', max_length=128)),
                ('output_rows', models.IntegerField(blank=True, null=True)),
                ('logs', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('kwargs_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'control_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
