# Generated by Django 5.2.16 on 2026-08-03 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(max_length=512)),
                ('key_prefix', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('scopes', models.JSONField(default=list)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'control_apikey',
                'ordering': ['-created_at'],
            },
        ),
    ]
