"""Shared wire, time, and cache budgets for theorem.layout.v1."""

MAX_LAYOUT_REQUEST_BYTES = 2 * 1024 * 1024
MAX_LAYOUT_RESPONSE_BYTES = 2 * 1024 * 1024
LAYOUT_REQUEST_TIMEOUT_SECONDS = 10.0
LAYOUT_GRAPHVIZ_MAX_SECONDS = 8.0
LAYOUT_CACHE_SOCKET_TIMEOUT_SECONDS = 0.25
LAYOUT_CACHE_MIN_WRITE_BUDGET_SECONDS = 0.05
LAYOUT_REQUEST_DEADLINE_ATTRIBUTE = "_theorem_layout_request_deadline"
LAYOUT_COMPUTE_PATH = "/internal/layout/compute"
