# Generated by Django 5.2.17 on 2026-09-03 21:27
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trajectory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_key", models.CharField(max_length=255)),
                ("trace_digest", models.CharField(max_length=71)),
                ("reward", models.FloatField()),
                ("metrics", models.JSONField(default=dict)),
                ("arrow_shard_key", models.CharField(max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "control_trajectory",
                "ordering": ["run_id", "task_key", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("eval", "Evaluation"),
                            ("prime_rl.train", "prime-rl training"),
                        ],
                        max_length=32,
                    ),
                ),
                ("operation_id", models.CharField(max_length=128)),
                ("taskset_ref", models.CharField(max_length=512)),
                ("config_digest", models.CharField(max_length=71)),
                ("config_json", models.JSONField(default=dict)),
                (
                    "image_digest",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("pod_id", models.CharField(blank=True, default="", max_length=191)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("artifact_keys", models.JSONField(blank=True, default=list)),
                ("artifact_descriptors", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_runs",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "control_trainingrun",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GraderVerdict",
            fields=[
                (
                    "trajectory",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="grader_verdict",
                        serialize=False,
                        to="theorem_rl.trajectory",
                    ),
                ),
                ("resolved", models.FloatField()),
                ("metric_values", models.JSONField(default=dict)),
                ("tripwire_flags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "control_graderverdict",
            },
        ),
        migrations.AddField(
            model_name="trajectory",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trajectories",
                to="theorem_rl.trainingrun",
            ),
        ),
        migrations.AddIndex(
            model_name="trajectory",
            index=models.Index(
                fields=["run", "task_key"], name="control_trajectory_task_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="trajectory",
            constraint=models.UniqueConstraint(
                fields=("run", "trace_digest"), name="control_trajectory_run_trace_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingrun",
            index=models.Index(
                fields=["tenant", "status", "created_at"],
                name="control_trainrun_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingrun",
            constraint=models.UniqueConstraint(
                fields=("tenant", "operation_id"),
                name="control_trainingrun_tenant_operation_uniq",
            ),
        ),
    ]
